---
title: "FPKM_cor_heatmap"
author: "Chengqi(Charley) Wang"
output: html_document
---

*date: "2/3/2020"*
####loading previous saved FPKM data
```{r}
setwd('~/Documents/work/paper_write/genome_training/R_training/')
fpkm <- read.table('vehicle_drug_feature_counts.fpkm.txt',
                   header = T, sep = '\t', row.names = 1)
head(fpkm)
```
<br/><br/>

####biological correlation calculation and heatmap
```{r}
corF <- cor(fpkm)
corF
heatmap(corF)

##using heatmap.2 to draw heatmap
library(gplots)
heatmap.2(corF, Colv= F, dendrogram = 'row',
          trace = 'n',      ## hist plot line inside heatmap
          denscol = 'navy'  ## hist plot line in color key
          )

##change the direction of column lable
heatmap.2(corF, Colv= F, dendrogram = 'row',
          trace = 'n', 
          denscol = 'navy', srtCol = 0 ## the angel of y column lable
          )

## change the color of heatmap
colPlate <- colorRampPalette(c('red', 'white', 'navy'))(100)
heatmap.2(corF, Colv= F, dendrogram = 'row',
          trace = 'n',  
          denscol = 'navy', srtCol = 0, ## the angel of y column lable
          col = colPlate
          )

## removing the lable in the heatmap
## change the size of the key
heatmap.2(corF, Colv= F, dendrogram = 'row',
          trace = 'n',  
          denscol = NA, srtCol = 0, ## the angel of y column lable
          col = colPlate, 
          #------------#
          key.title = '',
          key.ylab = NA, key.xlab = NA,
          keysize=0.75, 
          #remove the y-axis#
          #key.par = list(mar = c(1,0.3,1,1))
          )
```
<br/><br/>

####Drawing heatmap by ggplot
```{r}
corF <- cor(fpkm)
corF

##load package
library(reshape2)
melted_corF <- melt(corF) # change the correlation matrix to the pair 
length(corF)
nrow(melted_corF)

#heatmap drawing
library(ggplot2)
ggplot(data = melted_corF, aes(x=Var1, y=Var2, fill=value)) + 
  geom_tile()     

# Get lower triangular of the correlation matrix
get_upper_tri<-function(cormat){
  cormat[lower.tri(cormat)] <- NA
  return(cormat)
}

# Only keep lower triangular
upper_tri        <- get_upper_tri(corF)
melted_upper_tri <- melt( upper_tri )


ggplot(data = melted_upper_tri, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+
  scale_fill_gradient2(low = "navy", high = "red", mid = "white", 
                       midpoint = 0.9, limit = c(0.8,1), 
                       #space = "Lab", 
                       name="Pearson\nCorrelation") +
  theme_minimal()+ 
  theme(axis.text.x = element_text(angle = 45, vjust = 1, 
                                   size = 12, hjust = 1))+
  coord_fixed()



```



